types:
- types/*
- docs/_types/*
- test/type-*.bats
documentation:
- docs/**/*
core:
- lib/**/*
- bin/bork
- test/declare-*.bats
- test/fn-*.bats
- test/help-*.bats
- test/helpers.bats
packages:
- pkg/**/*
- .fpm