name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: Fixed
    label: bug
  - title: Added
    label: feature
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  $CHANGES