name: Build manpage

on:
  push:
    paths:
      - .github/workflows/build_manpage.yml
      - docs/bork.1.ronn
    branches:
      - main

jobs:
  update-manpage:
    runs-on: ubuntu-latest
    if: github.repository == 'skylarmacdonald/bork'
    steps:
    - uses: actions/checkout@v2
    - name: Install ronn
      run: gem install ronn
    - name: Generate man page
      run: |
        ronn -r --manual=bork --organization="Skylar MacDonald" docs/bork.1.ronn
        sed -i 's/<code>/\\fB/g' docs/bork.1
        sed -i 's/<var>/\\fI/g' docs/bork.1
        sed -Ei 's/<\/(code|var)>/\\fR/g' docs/bork.1
    - name: Upload compiled man page
      uses: actions/upload-artifact@v2
      with:
        path: docs/bork.1