name: Danger

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:
  push:
    branches:
    - bug/*
    - feature/*
    - docs/*

jobs:
  danger:
    name: 'Danger'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
    - name: Install dependencies
      run: |
        gem install danger
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: danger
