name: Homebrew formula
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v1
      with:
        formula-name: bork
        tag-name: ${{ github.event.inputs.tag-name }}
        download-url: https://github.com/borksh/bork/archive/${{ github.event.inputs.tag-name }}.tar.gz
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}