name: Homebrew formula
on:
  release: { types: [published] }
  workflow_dispatch:

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v1
      with:
        formula-name: bork
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}