name: Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: brew install bats # should work on GitHub Ubuntu runners
    - name: Check bash version
      run: bash --version
      shell: bash
    - name: Run bats test
      run: bats --tap test
      shell: bash
