name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bats
      run: sudo apt install -y bats
    - name: Check bash version
      run: bash --version
    - name: Run bats test
      run: bats --tap test
